### ISSUE TITLE
Add POD to this module

### ISSUE THREAD

**Issue by zostay** [zostay/Bot-Backbone-Service-GlotIO#1]
See one of these modules for style examples to emulate:
- https://github.com/zostay/Bot-Backbone-Service-Web/blob/master/lib/Bot/Backbone/Service/Web/LinkTitle.pm
- https://github.com/zostay/Bot-Backbone-Service-Fact/blob/master/lib/Bot/Backbone/Service/Fact/Keyword.pm
- https://github.com/gitpan/Bot-Backbone-Service-OFun/blob/master/lib/Bot/Backbone/Service/OFun/Dice.pm

**Comment by polettix** [comment]
I guess my patch will not count against this year's Hacktoberfest... but it would be nice to hear from you about it and get feedback anyway 😁

**Comment by polettix** [comment]
I see this was merged... I'd suggest to close the issue 😄
